FROM docker.io/golang:latest as builder

RUN --mount=type=bind,source=/,target=/register-ilugc,rw sh -c 'cd /register-ilugc && make' && tar cvf /register-ilugc.tar /register-ilugc/src/cmd/register /register-ilugc/static

FROM docker.io/alpine:latest
COPY --from=builder /register-ilugc.tar /register-ilugc.tar
RUN tar xvf /register-ilugc.tar -C /
VOLUME ["/data"]
EXPOSE 2203
WORKDIR /data
ENTRYPOINT ["/register-ilugc/src/cmd/register"]
